### ISSUE TITLE
Add optional usernames to profiles.

### ISSUE THREAD

**Issue by Precisi** [jkenlooper/puzzle-massive#51]
It would be nice for a private site to have the option to add usernames (maybe as an extra field in the profile) or link to a facebook login or something. Then people can see who is who on the icon list as it's easy to lose traffic of which icon belongs to who.

**Comment by jkenlooper** [comment]
A couple of example mock-ups that also show a custom background color for the bit icons.  
![profile-bit-with-name-example](https://user-images.githubusercontent.com/457827/58707525-7725ff00-8372-11e9-964f-7b9638857800.png)
![bit-icons-with-names-and-background-example](https://user-images.githubusercontent.com/457827/58707532-7c834980-8372-11e9-9a00-6e26d4d8d068.png)

This will require some modifications to the existing database schema to include storing the username along with the custom background color.  A custom set of background colors could be used and then players could have a unique combination of background color to bit icon.  This would allow more players to have bit icons and could further distinguish between players with the same bit icon by the background color.  
Slight feature change with adding the custom background color, but I think it could be done as part of this feature.

**Comment by jkenlooper** [comment]
Custom background color for bit icons will be a different feature.
