### ISSUE TITLE
Award puzzle instance slots to players that meet a minimum score

### ISSUE THREAD

**Issue by jkenlooper** [jkenlooper/puzzle-massive#87]
The site should have a configuration that will automatically assign a puzzle instance slot to players that get to a certain score.  This should also allow a site to be configured to not have this enabled if puzzle instance slots were restricted to only be manually assigned or bought.

When a site first starts up, it should check all existing players that might meet this threshold and assign puzzle instance slots to each if they don't already have one.

The player profile page should show a progress bar of how close they are in being awarded a puzzle instance slot.

A player should get a puzzle instance slot after their score has increased past the threshold.  It would be cool if they also got some kind of notification, but that wouldn't be required for this issue requirements.

**Comment by MadMaxim1** [comment]
Request a Puzzle Instant slot please.

Uncle Mike

**Comment by jkenlooper** [comment]
@MadMaxim1, Awarded to the player account Uncle Mike 2 since it was the more recent active one.  Also note that getting a score of 250 will automatically add a puzzle instance slot.  I'm a little slow on updating the content on the live site with this information.
